//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34209
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 
namespace GamesData {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://loiclacombe.com/emuconfig.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://loiclacombe.com/emuconfig.xsd", IsNullable=false)]
    public partial class SystemConfigRoot {
        
        private SystemNode[] systemNodeField;
        
        private Emulator[] emulatorField;
        
        private Library[] libraryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SystemNode")]
        public SystemNode[] SystemNode {
            get {
                return this.systemNodeField;
            }
            set {
                this.systemNodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Emulator")]
        public Emulator[] Emulator {
            get {
                return this.emulatorField;
            }
            set {
                this.emulatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Library")]
        public Library[] Library {
            get {
                return this.libraryField;
            }
            set {
                this.libraryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SystemGroup))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://loiclacombe.com/emuconfig.xsd")]
    public partial class SystemNode {
        
        private SystemNode[] itemsField;
        
        private string descriptionField;
        
        private bool enabledField;
        
        public SystemNode() {
            this.enabledField = true;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SystemGroup", typeof(SystemGroup))]
        [System.Xml.Serialization.XmlElementAttribute("SystemNode", typeof(SystemNode))]
        public SystemNode[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool Enabled {
            get {
                return this.enabledField;
            }
            set {
                this.enabledField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://loiclacombe.com/emuconfig.xsd")]
    public partial class SystemGroup : SystemNode {
        
        private EmulatedSystem[] emulatedSystemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("EmulatedSystem")]
        public EmulatedSystem[] EmulatedSystem {
            get {
                return this.emulatedSystemField;
            }
            set {
                this.emulatedSystemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://loiclacombe.com/emuconfig.xsd")]
    public partial class EmulatedSystem {
        
        private CompatibleEmulator compatibleEmulatorField;
        
        private string descriptionField;
        
        private string shortNameField;
        
        /// <remarks/>
        public CompatibleEmulator CompatibleEmulator {
            get {
                return this.compatibleEmulatorField;
            }
            set {
                this.compatibleEmulatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ShortName {
            get {
                return this.shortNameField;
            }
            set {
                this.shortNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://loiclacombe.com/emuconfig.xsd")]
    public partial class CompatibleEmulator {
        
        private string nameField;
        
        private string libraryNameField;
        
        private bool enabledField;
        
        public CompatibleEmulator() {
            this.enabledField = true;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string LibraryName {
            get {
                return this.libraryNameField;
            }
            set {
                this.libraryNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool Enabled {
            get {
                return this.enabledField;
            }
            set {
                this.enabledField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://loiclacombe.com/emuconfig.xsd")]
    public partial class Library {
        
        private string[] romExtensionField;
        
        private string nameField;
        
        private string libraryClassField;
        
        private string libraryFolderKeyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RomExtension")]
        public string[] RomExtension {
            get {
                return this.romExtensionField;
            }
            set {
                this.romExtensionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string LibraryClass {
            get {
                return this.libraryClassField;
            }
            set {
                this.libraryClassField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string LibraryFolderKey {
            get {
                return this.libraryFolderKeyField;
            }
            set {
                this.libraryFolderKeyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://loiclacombe.com/emuconfig.xsd")]
    public partial class Emulator {
        
        private string emulatorPathKeyField;
        
        private string cliParametersField;
        
        private string[] parametersFromKeysField;
        
        private string nameField;
        
        private string descriptionField;
        
        /// <remarks/>
        public string EmulatorPathKey {
            get {
                return this.emulatorPathKeyField;
            }
            set {
                this.emulatorPathKeyField = value;
            }
        }
        
        /// <remarks/>
        public string CliParameters {
            get {
                return this.cliParametersField;
            }
            set {
                this.cliParametersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ParametersFromKeys")]
        public string[] ParametersFromKeys {
            get {
                return this.parametersFromKeysField;
            }
            set {
                this.parametersFromKeysField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
}
