//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleanEmulatorFrontend.SqLiteCache
{
    using System;
    using System.Collections.Generic;
    
    public partial class base_path
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public base_path()
        {
            this.game_base_path = new HashSet<game_base_path>();
        }
    
        public long base_path_id { get; set; }
        public string bp_path { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<game_base_path> game_base_path { get; set; }
    }
}
