//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleanEmulatorFrontend.SqLiteCache
{
    using System;
    using System.Collections.Generic;
    
    public partial class game_base_path
    {
        public long game_id { get; set; }
        public Nullable<long> base_path_id { get; set; }
    
        public virtual base_path base_path { get; set; }
        public virtual game game { get; set; }
    }
}
