//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleanEmulatorFrontend.SQLiteCache
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_game
    {
        public System.Guid gguid { get; set; }
        public int played { get; set; }
        public int game_id { get; set; }
        public System.DateTime last_played_date { get; set; }
    }
}
