//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :2.0.50727.5485
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/namespace/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.w3.org/namespace/", IsNullable=false)]
public partial class mame {
    
    private game[] gameField;
    
    private string mameconfigField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("game")]
    public game[] game {
        get {
            return this.gameField;
        }
        set {
            this.gameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string mameconfig {
        get {
            return this.mameconfigField;
        }
        set {
            this.mameconfigField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/namespace/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.w3.org/namespace/", IsNullable=false)]
public partial class game {
    
    private description descriptionField;
    
    private year yearField;
    
    private manufacturer manufacturerField;
    
    private biosset[] biossetField;
    
    private rom[] romField;
    
    private disk[] diskField;
    
    private device_ref[] device_refField;
    
    private sample[] sampleField;
    
    private chip[] chipField;
    
    private display[] displayField;
    
    private sound soundField;
    
    private input inputField;
    
    private dipswitch[] dipswitchField;
    
    private configuration[] configurationField;
    
    private port[] portField;
    
    private adjuster[] adjusterField;
    
    private driver driverField;
    
    private device[] deviceField;
    
    private slot[] slotField;
    
    private softwarelist[] softwarelistField;
    
    private ramoption[] ramoptionField;
    
    private string sampleofField;
    
    /// <remarks/>
    public description description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    public year year {
        get {
            return this.yearField;
        }
        set {
            this.yearField = value;
        }
    }
    
    /// <remarks/>
    public manufacturer manufacturer {
        get {
            return this.manufacturerField;
        }
        set {
            this.manufacturerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("biosset")]
    public biosset[] biosset {
        get {
            return this.biossetField;
        }
        set {
            this.biossetField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("rom")]
    public rom[] rom {
        get {
            return this.romField;
        }
        set {
            this.romField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("disk")]
    public disk[] disk {
        get {
            return this.diskField;
        }
        set {
            this.diskField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("device_ref")]
    public device_ref[] device_ref {
        get {
            return this.device_refField;
        }
        set {
            this.device_refField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("sample")]
    public sample[] sample {
        get {
            return this.sampleField;
        }
        set {
            this.sampleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("chip")]
    public chip[] chip {
        get {
            return this.chipField;
        }
        set {
            this.chipField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("display")]
    public display[] display {
        get {
            return this.displayField;
        }
        set {
            this.displayField = value;
        }
    }
    
    /// <remarks/>
    public sound sound {
        get {
            return this.soundField;
        }
        set {
            this.soundField = value;
        }
    }
    
    /// <remarks/>
    public input input {
        get {
            return this.inputField;
        }
        set {
            this.inputField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("dipswitch")]
    public dipswitch[] dipswitch {
        get {
            return this.dipswitchField;
        }
        set {
            this.dipswitchField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("configuration")]
    public configuration[] configuration {
        get {
            return this.configurationField;
        }
        set {
            this.configurationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("port")]
    public port[] port {
        get {
            return this.portField;
        }
        set {
            this.portField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("adjuster")]
    public adjuster[] adjuster {
        get {
            return this.adjusterField;
        }
        set {
            this.adjusterField = value;
        }
    }
    
    /// <remarks/>
    public driver driver {
        get {
            return this.driverField;
        }
        set {
            this.driverField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("device")]
    public device[] device {
        get {
            return this.deviceField;
        }
        set {
            this.deviceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("slot")]
    public slot[] slot {
        get {
            return this.slotField;
        }
        set {
            this.slotField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("softwarelist")]
    public softwarelist[] softwarelist {
        get {
            return this.softwarelistField;
        }
        set {
            this.softwarelistField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ramoption")]
    public ramoption[] ramoption {
        get {
            return this.ramoptionField;
        }
        set {
            this.ramoptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string sampleof {
        get {
            return this.sampleofField;
        }
        set {
            this.sampleofField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/namespace/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.w3.org/namespace/", IsNullable=false)]
public partial class description {
    
    private string[] textField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/namespace/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.w3.org/namespace/", IsNullable=false)]
public partial class year {
    
    private string[] textField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/namespace/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.w3.org/namespace/", IsNullable=false)]
public partial class manufacturer {
    
    private string[] textField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/namespace/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.w3.org/namespace/", IsNullable=false)]
public partial class biosset {
    
    private biossetDefault defaultField;
    
    private bool defaultFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public biossetDefault @default {
        get {
            return this.defaultField;
        }
        set {
            this.defaultField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool defaultSpecified {
        get {
            return this.defaultFieldSpecified;
        }
        set {
            this.defaultFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/namespace/")]
public enum biossetDefault {
    
    /// <remarks/>
    yes,
    
    /// <remarks/>
    no,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/namespace/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.w3.org/namespace/", IsNullable=false)]
public partial class rom {
    
    private romOptional optionalField;
    
    private bool optionalFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public romOptional optional {
        get {
            return this.optionalField;
        }
        set {
            this.optionalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool optionalSpecified {
        get {
            return this.optionalFieldSpecified;
        }
        set {
            this.optionalFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/namespace/")]
public enum romOptional {
    
    /// <remarks/>
    yes,
    
    /// <remarks/>
    no,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/namespace/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.w3.org/namespace/", IsNullable=false)]
public partial class disk {
    
    private diskOptional optionalField;
    
    private bool optionalFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public diskOptional optional {
        get {
            return this.optionalField;
        }
        set {
            this.optionalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool optionalSpecified {
        get {
            return this.optionalFieldSpecified;
        }
        set {
            this.optionalFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/namespace/")]
public enum diskOptional {
    
    /// <remarks/>
    yes,
    
    /// <remarks/>
    no,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/namespace/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.w3.org/namespace/", IsNullable=false)]
public partial class device_ref {
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/namespace/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.w3.org/namespace/", IsNullable=false)]
public partial class sample {
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/namespace/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.w3.org/namespace/", IsNullable=false)]
public partial class chip {
    
    private string clockField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string clock {
        get {
            return this.clockField;
        }
        set {
            this.clockField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/namespace/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.w3.org/namespace/", IsNullable=false)]
public partial class display {
    
    private string vbstartField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string vbstart {
        get {
            return this.vbstartField;
        }
        set {
            this.vbstartField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/namespace/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.w3.org/namespace/", IsNullable=false)]
public partial class sound {
    
    private string channelsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string channels {
        get {
            return this.channelsField;
        }
        set {
            this.channelsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/namespace/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.w3.org/namespace/", IsNullable=false)]
public partial class input {
    
    private control[] controlField;
    
    private string coinsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("control")]
    public control[] control {
        get {
            return this.controlField;
        }
        set {
            this.controlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string coins {
        get {
            return this.coinsField;
        }
        set {
            this.coinsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/namespace/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.w3.org/namespace/", IsNullable=false)]
public partial class control {
    
    private string ways3Field;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ways3 {
        get {
            return this.ways3Field;
        }
        set {
            this.ways3Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/namespace/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.w3.org/namespace/", IsNullable=false)]
public partial class dipswitch {
    
    private dipvalue[] dipvalueField;
    
    private string maskField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("dipvalue")]
    public dipvalue[] dipvalue {
        get {
            return this.dipvalueField;
        }
        set {
            this.dipvalueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string mask {
        get {
            return this.maskField;
        }
        set {
            this.maskField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/namespace/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.w3.org/namespace/", IsNullable=false)]
public partial class dipvalue {
    
    private dipvalueDefault defaultField;
    
    private bool defaultFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public dipvalueDefault @default {
        get {
            return this.defaultField;
        }
        set {
            this.defaultField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool defaultSpecified {
        get {
            return this.defaultFieldSpecified;
        }
        set {
            this.defaultFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/namespace/")]
public enum dipvalueDefault {
    
    /// <remarks/>
    yes,
    
    /// <remarks/>
    no,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/namespace/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.w3.org/namespace/", IsNullable=false)]
public partial class configuration {
    
    private confsetting[] confsettingField;
    
    private string maskField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("confsetting")]
    public confsetting[] confsetting {
        get {
            return this.confsettingField;
        }
        set {
            this.confsettingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string mask {
        get {
            return this.maskField;
        }
        set {
            this.maskField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/namespace/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.w3.org/namespace/", IsNullable=false)]
public partial class confsetting {
    
    private confsettingDefault defaultField;
    
    private bool defaultFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public confsettingDefault @default {
        get {
            return this.defaultField;
        }
        set {
            this.defaultField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool defaultSpecified {
        get {
            return this.defaultFieldSpecified;
        }
        set {
            this.defaultFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/namespace/")]
public enum confsettingDefault {
    
    /// <remarks/>
    yes,
    
    /// <remarks/>
    no,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/namespace/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.w3.org/namespace/", IsNullable=false)]
public partial class port {
    
    private analog[] analogField;
    
    private string tagField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("analog")]
    public analog[] analog {
        get {
            return this.analogField;
        }
        set {
            this.analogField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string tag {
        get {
            return this.tagField;
        }
        set {
            this.tagField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/namespace/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.w3.org/namespace/", IsNullable=false)]
public partial class analog {
    
    private string maskField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string mask {
        get {
            return this.maskField;
        }
        set {
            this.maskField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/namespace/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.w3.org/namespace/", IsNullable=false)]
public partial class adjuster {
    
    private string defaultField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string @default {
        get {
            return this.defaultField;
        }
        set {
            this.defaultField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/namespace/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.w3.org/namespace/", IsNullable=false)]
public partial class driver {
    
    private driverSavestate savestateField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public driverSavestate savestate {
        get {
            return this.savestateField;
        }
        set {
            this.savestateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/namespace/")]
public enum driverSavestate {
    
    /// <remarks/>
    supported,
    
    /// <remarks/>
    unsupported,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/namespace/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.w3.org/namespace/", IsNullable=false)]
public partial class device {
    
    private instance[] instanceField;
    
    private extension[] extensionField;
    
    private string interfaceField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("instance")]
    public instance[] instance {
        get {
            return this.instanceField;
        }
        set {
            this.instanceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("extension")]
    public extension[] extension {
        get {
            return this.extensionField;
        }
        set {
            this.extensionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string @interface {
        get {
            return this.interfaceField;
        }
        set {
            this.interfaceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/namespace/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.w3.org/namespace/", IsNullable=false)]
public partial class instance {
    
    private string briefnameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string briefname {
        get {
            return this.briefnameField;
        }
        set {
            this.briefnameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/namespace/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.w3.org/namespace/", IsNullable=false)]
public partial class extension {
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/namespace/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.w3.org/namespace/", IsNullable=false)]
public partial class slot {
    
    private slotoption[] slotoptionField;
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("slotoption")]
    public slotoption[] slotoption {
        get {
            return this.slotoptionField;
        }
        set {
            this.slotoptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/namespace/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.w3.org/namespace/", IsNullable=false)]
public partial class slotoption {
    
    private slotoptionDefault defaultField;
    
    private bool defaultFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public slotoptionDefault @default {
        get {
            return this.defaultField;
        }
        set {
            this.defaultField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool defaultSpecified {
        get {
            return this.defaultFieldSpecified;
        }
        set {
            this.defaultFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/namespace/")]
public enum slotoptionDefault {
    
    /// <remarks/>
    yes,
    
    /// <remarks/>
    no,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/namespace/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.w3.org/namespace/", IsNullable=false)]
public partial class softwarelist {
    
    private string filterField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string filter {
        get {
            return this.filterField;
        }
        set {
            this.filterField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/namespace/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.w3.org/namespace/", IsNullable=false)]
public partial class ramoption {
    
    private string defaultField;
    
    private string[] textField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string @default {
        get {
            return this.defaultField;
        }
        set {
            this.defaultField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
}
