/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace CleanEmulatorFrontend.Cache.Data
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class Game : TBase
  {
    private string _Description;
    private string _BasePath;
    private string _LaunchPath;

    public string Description
    {
      get
      {
        return _Description;
      }
      set
      {
        __isset.Description = true;
        this._Description = value;
      }
    }

    public string BasePath
    {
      get
      {
        return _BasePath;
      }
      set
      {
        __isset.BasePath = true;
        this._BasePath = value;
      }
    }

    public string LaunchPath
    {
      get
      {
        return _LaunchPath;
      }
      set
      {
        __isset.LaunchPath = true;
        this._LaunchPath = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool Description;
      public bool BasePath;
      public bool LaunchPath;
    }

    public Game() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.String) {
              Description = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.String) {
              BasePath = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.String) {
              LaunchPath = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("Game");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (Description != null && __isset.Description) {
        field.Name = "Description";
        field.Type = TType.String;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(Description);
        oprot.WriteFieldEnd();
      }
      if (BasePath != null && __isset.BasePath) {
        field.Name = "BasePath";
        field.Type = TType.String;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(BasePath);
        oprot.WriteFieldEnd();
      }
      if (LaunchPath != null && __isset.LaunchPath) {
        field.Name = "LaunchPath";
        field.Type = TType.String;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(LaunchPath);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("Game(");
      bool __first = true;
      if (Description != null && __isset.Description) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Description: ");
        __sb.Append(Description);
      }
      if (BasePath != null && __isset.BasePath) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("BasePath: ");
        __sb.Append(BasePath);
      }
      if (LaunchPath != null && __isset.LaunchPath) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("LaunchPath: ");
        __sb.Append(LaunchPath);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
